
all: spikein1 spikein2 mouse vignettes manuscript clean

spikein1:
	R CMD BATCH scripts/spikein1/spikein1_preprocess.R
	R CMD BATCH scripts/spikein1/spikein1_msqrob2tmt.R
	R CMD BATCH scripts/spikein1/spikein1_msstatstmt.R
	R CMD BATCH scripts/spikein1/spikein1_deqms.R
	R CMD BATCH scripts/spikein1/spikein1_mstrawler.R
	R CMD BATCH scripts/spikein1/spikein1_compare_preprocessing.R
	R CMD BATCH scripts/spikein1/spikein1_figures.R

spikein2:
	R CMD BATCH scripts/spikein2/spikein2_preprocess.R
	R CMD BATCH scripts/spikein2/spikein2_msqrob2tmt.R
	R CMD BATCH scripts/spikein2/spikein2_msstatstmt.R
	R CMD BATCH scripts/spikein2/spikein2_deqms.R
	R CMD BATCH scripts/spikein2/spikein2_mstrawler.R
	R CMD BATCH scripts/spikein2/spikein2_figures.R

mouse:
	R CMD BATCH scripts/mouse/mouse_msqrob2tmt.R
	R CMD BATCH scripts/mouse/mouse_msqrob2tmt_mixture.R
	R CMD BATCH scripts/mouse/mouse_msstatstmt.R
	R CMD BATCH scripts/mouse/mouse_figures.R

manuscript:
	quarto render paper/manuscript.qmd

vignettes:
	quarto render vignettes/spikein1.qmd
	quarto render vignettes/mouse.qmd

# Remove any useless artefacts
# - MSstatsTMT_*: log files generated by MSstatsTMT
# - Factor_*.csv, ColAdjustment*.csv, Simple.csv: files generated
#   by msTrawler
# - *.Rout: log files generated by R CMD BATCH
clean:
	@find . -type f -name "MSstatsTMT_*.log" -exec rm -rf {} \;
	@find . -type f -name "Factor_*.csv" -exec rm -rf {} \;
	@find . -type f -name "ColAdjustment*.csv" -exec rm -rf {} \;
	@find . -type f -name "Simple.csv" -exec rm -rf {} \;
	@find . -type f -name "*.Rout" -exec rm -rf {} \;
	@find . -type f -name ".RData" -exec rm -rf {} \;
	@rm -rf "Rplots.pdf" \;
